##
# Cat Facts API Server - development configuration
#

logging:
  level: INFO
  appenders:
    - type: console

datasource: postgresql
load_fixtures: false

# Database Configuration
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost/catfacts_dev
  user: catfacts
  password: catfacts
